spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath://shared
  profiles: dev, prod
  profiles.include: native
  security:
    user:
      password: user

server:
  port: 8888

