language: java
jdk:
  - openjdk11

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

install:
  - nvm install 8.9.3
before_script:
  - chmod +x gradlew
script:
  - ./gradlew clean check jacocoTestReport testCI
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false