version: '3.0'
services:
  config:
    build: config
    ports:
      - 8888:8888

  registry:
    build: registry

  ui-service:
    build: ui-service

  account-service:
    build: account-service
    ports:
      - 6000:6000
