version: '3'
services:
  config:
    image: bandits/bandit-config
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    image: bandits/bandit-registry
    restart: always
    depends_on:
      - config
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  ui-service:
    image: bandits/bandit-ui-service
    restart: always
    depends_on:
      - config
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"