version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: chmod +x gradlew
      - run:
          name: Build app
          command: ./gradlew assemble
      - save_cache:
          paths:
              - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}

  test_ut:
    docker:
      - image: circleci/openjdk:11.0.2-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: chmod +x gradlew
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
      - run:
          name: Unit Tests
          command: ./gradlew check jacocoTestReport
      - run:
          name: Codecov report
          command: bash <(curl -s https://codecov.io/bash)
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-ut

  test_e2e:
    docker:
      - image: circleci/openjdk:11.0.2-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-e2e
#      - run:
#          name: e2e
#          command: ./gradlew e2etest

  stats:
    docker:
      - image: circleci/openjdk:11.0.2-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-ut
      # move here codecov

  deploy:
    docker:
      - image: circleci/openjdk:11.0.2-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout

workflows:
  version: 2
  branch_pipeline:
    jobs:
      - build
      - test_ut:
          requires:
            - build
      - test_e2e:
          requires:
            - build
      - stats:
          requires:
            - test_ut
            - test_e2e
      - deploy:
          requires:
            - test_ut
            - test_e2e