hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  prefix: '/1.0/api'
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
      path: /uaa/**
      url: http://auth-service:5000
      stripPrefix: false
      sensitiveHeaders:
    account-service:
      path: /accounts/**
      url: http://account-service:5000
      stripPrefix: false
      sensitiveHeaders:

server:
  port: 4000
